baseURL = 'https://nefortner.com'
languageCode = 'en-us'
title = "Nate's Cybersecurity Blog"

theme = 'LoveIt'

googleAnalytics = 'G-7ZSFRQTX7E'




[params]
  author = 'Nate Fortner'
  pathPrompt = 'nate@nefortner.com'
  version = '2.0.X'

  footerCopyrightName = 'Nate Fortner'
  footerCopyrightLicense = 'CC BY 4.0'
  footerCopyrightLicenseLink = 'https://creativecommons.org/licenses/by/4.0'
  footerBuildTime = 'true'
  footerAttributionLink = '/attribution'
  
  description = "Nate Fortner's personal blog"

  defaultTheme = 'auto'

  gitRepo = 'https://github.com/bsasealteam6/nefortner.com'

  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    # title = "uBlogger"
    # whether to omit favicon resource links
    noFavicon = true
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
  [params.search]
    enable = false
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # uBlogger NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # uBlogger NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # uBlogger NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # uBlogger NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
  showPath = 'true'
  # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # uBlogger NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Nate's Cybersecurity Blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""

  # Footer config
  [params.footer]
    enable = true
    # uBlogger NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # uBlogger NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # uBlogger NEW | 0.2.0 whether to show copyright info
    copyright = true
    # uBlogger NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2022
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
  [params.home]
    # uBlogger NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
    #   avatarURL = "/images/avatar.png"
      # uBlogger CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "Welcome to my blog"
      # whether to show social links
      social = true
      # uBlogger NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = "This site may contain samples of code from malware for educational purposes only. The author does not condone usage of this code for malicious means."
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # uBlogger DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false
    # Social config about the author
  [params.social]
    GitHub = "bsasealteam6"
    Linkedin = "nefortner"
    # Twitter = "xxxx"
    # Instagram = "xxxx"
    # Facebook = "xxxx"
    # Telegram = "xxxx"
    # Medium = ""
    # Gitlab = ""
    # Youtubelegacy = ""
    # Youtubecustom = ""
    # Youtubechannel = ""
    # Tumblr = ""
    # Quora = ""
    # Keybase = ""
    # Pinterest = ""
    # Reddit = ""
    # Codepen = ""
    # FreeCodeCamp = ""
    Bitbucket = "bsasealteam6"
    # Stackoverflow = ""
    # Weibo = ""
    # Odnoklassniki = ""
    # VK = ""
    # Flickr = ""
    # Xing = ""
    # Snapchat = ""
    # Soundcloud = ""
    # Spotify = ""
    # Bandcamp = ""
    # Paypal = ""
    # Fivehundredpx = ""
    # Mix = ""
    # Goodreads = ""
    # Lastfm = ""
    # Foursquare = ""
    # Hackernews = ""
    # Kickstarter = ""
    # Patreon = ""
    # Steam = ""
    # Twitch = ""
    # Strava = ""
    # Skype = ""
    # Whatsapp = ""
    # Zhihu = ""
    # Douban = ""
    # Angellist = ""
    # Slidershare = ""
    # Jsfiddle = ""
    # Deviantart = ""
    # Behance = ""
    # Dribbble = ""
    # Wordpress = ""
    # Vine = ""
    # Googlescholar = ""
    # Researchgate = ""
    # Mastodon = ""
    # Thingiverse = ""
    # Devto = ""
    # Gitea = ""
    # XMPP = ""
    # Matrix = ""
    # Bilibili = ""
    Email = "contact@nefortner.com"
    RSS = true # uBlogger NEW | 0.2.0
  [params.page]
    # uBlogger NEW | 1.0.0 main subject for articles, by default classic. more on themes}
    theme = "classic"
    # uBlogger NEW | 0.2.0 whether to hide a page from home page
    hiddenFromHomePage = false
    # uBlogger NEW | 0.2.0 whether to hide a page from search results
    hiddenFromSearch = false
    # uBlogger NEW | 1.2.0 Allows you to hide the preview image on the article page
    hiddenFeaturedImage = false
    # uBlogger NEW | 0.2.0 whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    # uBlogger NEW | 0.2.0 whether to enable the ruby extended syntax
    ruby = true
    # uBlogger NEW | 0.2.0 whether to enable the fraction extended syntax
    fraction = true
    # uBlogger NEW | 0.2.0 whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # uBlogger NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = false
    # uBlogger NEW | 1.1.0 Post display settings on the page
    [params.summary]
      # uBlogger NEW | 1.1.0 Display previews on the page of posts
      hiddenImage = false
      # uBlogger NEW | 1.1.0 Allows you to hide the description
      hiddenDescription = false
      # uBlogger NEW | 1.1.0 Allows you to hide the title
      hiddenTitle = false
    # uBlogger NEW | 1.1.0 Tag display settings
    [params.summary.tags]
      # uBlogger NEW | 1.1.0 One of the options for displaying tags
      theme = "image"
      # uBlogger NEW | 1.1.0 Text color
      color = "white"
      # uBlogger NEW | 1.1.0 Backing color
      background = "black"
      # uBlogger NEW | 1.1.0 Tag transparency
      transparency = 0.9
    # uBlogger NEW | 1.2.0 Fasting time display
    [params.timeAgo]
      enable = "false"
      lang = "en"
    # uBlogger NEW | 0.2.0 Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # uBlogger NEW | 0.2.9 whether to keep the static table of the contents in front of the post
      keepStatic = true
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    # uBlogger CHANGED | 0.2.0 KaTeX mathematical formulas
    [params.page.math]
      enable = true
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
    # uBlogger NEW | 0.2.0 Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
    # uBlogger NEW | 0.2.0 Mapbox GL JS config
    [params.page.mapbox]
      # access token of Mapbox GL JS
      accessToken = ""
      # style for the light theme
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # style for the dark theme
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # whether to add NavigationControl
      navigation = true
      # whether to add GeolocateControl
      geolocate = true
      # whether to add ScaleControl
      scale = true
      # whether to add FullscreenControl
      fullscreen = true
    # uBlogger CHANGED | 0.2.0 social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = true
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false
    # uBlogger NEW | 0.2.7 Third-party library config
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/"
        # Or
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/"
        # Or
        # someJavascript = "https://cdn.example.com/some.js"
    # uBlogger CHANGED | 0.2.10 Page SEO config
    [params.page.seo]
      # image URL
      images = []
      # Publisher info
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""
  #Comment settings (Currently Disabled)
  [params.page.comment]
      enable = true
      # uBlogger NEW | 1.0.0
      # Remark42 comment config
      [params.page.comment.remark42]
        enable = false
        # the location of your server with Remark42
        host = "https://remark.example.com"
        # remark42 supports comments for several sites at once, this identifier indicates which site to display comments for.
        site = "you_site_key"
        # design theme
        theme = "light"
        # language
        locale = "en"
        # enable or disable smiley support
        emailSubscribe = "true"
      # Disqus comment config
      [params.page.comment.disqus]
        # uBlogger NEW | 0.1.1
        enable = false
        # Disqus shortname to use Disqus in posts
        shortname = ""
      # Gitalk comment config
      [params.page.comment.gitalk]
        # uBlogger NEW | 0.1.1
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine comment config
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        # uBlogger NEW | 0.2.6 emoji data file name, default is "google.yml"
        # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
        # located in "themes/uBlogger/assets/data/emoji/" directory
        # you can store your own data files in the same path under your project:
        # "assets/data/emoji/"
        emoji = ""
      # Facebook comment config
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      # uBlogger NEW | 0.2.0 Telegram comments config
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      # uBlogger NEW | 0.2.0 Commento comment config
      [params.page.comment.commento]
        enable = false
      # uBlogger NEW | 0.2.5 Utterances comment config
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = "bsasealteam6/nefortner.com-comments"
        issueTerm = "pathname"
        label = "Test"
        lightTheme = "github-light"
        darkTheme = "github-dark"
      [params.page.comment.giscus]
        # You can refer to the official documentation of giscus to use the following configuration.
        # 你可以参考官方文档来使用下列配置
        enable = true
        repo = "bsasealteam6/nefortner.com"
        repoId = "R_kgDOHZB8qg"
        category = "Comments"
        categoryId = "DIC_kwDOHZB8qs4CT_5s"
        # automatically adapt the current theme i18n configuration when empty
        # 为空时自动适配当前主题 i18n 配置
        lang = ""
        mapping = "pathname"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        lazyLoading = false
        lightTheme = "light"
        darkTheme = "dark"
  [params.verification]
    # google = ""
    # bing = ""
    yandex = "ca384d573446707b"
    pinterest = "f804419188f48bea11d15b5a9df82b8e"
    # baidu = ""
  [params.seo]
    # image URL
    image = ""
    # thumbnail URL
    thumbnailUrl = ""
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-7ZSFRQTX7E"
      gTag = "G-7ZSFRQTX7E"
      # whether to anonymize IP
      anonymizeIP = false
    # Fathom Analytics
    # [params.analytics.fathom]
    #   id = ""
    #   # server url for your tracker if you're self hosting
    #   server = ""
    # # uBlogger NEW | 1.0.0
    # # Yandex.Metrika
    # [params.analytics.yandex]
    #   # your meter number
    #   id = ""
  [params.cookieconsent]
    enable = false
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""
  [params.cdn]
    # CDN data file name, disabled by default
    # ("jsdelivr.yml")
    # located in "themes/uBlogger/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = ""
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false
# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6  
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

    
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
[menu]
  [[menu.main]]
    identifier = 'posts'
    pre = ''
    post = ''
    name = 'Posts'
    url = '/posts/'
    title = 'Blog Posts'
    weight = 1
#  [[menu.main]]
#    identifier = 'about'
#    pre = ''
#    post = ''
#    name = 'About'
#    url = '/about/'
#    title = 'About Nate'
#    weight = 2
  [[menu.main]]
    identifier = 'resume'
    pre = ''
    post = ''
    name = 'Resume'
    url = '/resume/'
    title = 'Nate Resume'
    weight = 3
  [[menu.main]]
    parent = 'posts'
    identifier = 'conferences'
    pre = ''
    post = ''
    name = 'Conferences'
    url = '/categories/conferences/'
    title = 'Conferences'
    weight = 1
[minify]
  disableXML = true
  minifyOutput = true

